filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/myapp/syslog.log
    tags: ["ubuntu_syslog"]

output.elasticsearch:
  enabled: false

output.logstash:
  hosts: ["log:5044"]