filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/myapp/*.log
    tags: ["ubuntu_syslog"]

output.elasticsearch:
  enabled: false

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]
